

services:
  python:
    image: python:3.10-slim
    container_name: python
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: tail -f /dev/null
    stdin_open: true
    tty: true